--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OutiServer/PMMPLandManager
build-by-default: true
branches:
- main
projects:
  PMMPLandManager:
    path: ""
    lint:
      phpstan: false
...
